DROP TABLE IF EXISTS post;

CREATE TABLE IF NOT EXISTS post
(
    id SERIAL PRIMARY KEY NOT NULL,
    word VARCHAR(255) NOT NULL,
    pinyin VARCHAR(255),
    def VARCHAR(255) NOT NULL,
    example VARCHAR(255)
);